spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud?useSSL=false&serverTimezone=UTC
    username: yibo
    password: Y1b0@Pass!
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 9090

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  level:
    org.springframework.security: DEBUG
file:
  upload-dir: /home/yibo/Desktop/cloud-project/springboot/uploads
